### ISSUE TITLE
The output tensor shape of Slice Op is None

### ISSUE THREAD

**Issue by JiayiFu** [onnx/onnx-tensorflow#526]
**Describe the bug**

I have an ONNX model which has two Slice Op connected in series. When I use to convert it to the TensorFlow model. It crashed and show the followed error logs:

> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/fujiayi/Project/GitHub/onnx-tensorflow/example/onnx_to_tf.py", line 6, in <module>
    tf_rep = prepare(onnx_model)  # prepare tf representation
  File "/data1/fujiayi/Project/GitHub/onnx-tensorflow/onnx_tf/backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/data1/fujiayi/Project/GitHub/onnx-tensorflow/onnx_tf/backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/data1/fujiayi/Project/GitHub/onnx-tensorflow/onnx_tf/backend.py", line 143, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/data1/fujiayi/Project/GitHub/onnx-tensorflow/onnx_tf/backend.py", line 239, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/data1/fujiayi/Project/GitHub/onnx-tensorflow/onnx_tf/handlers/handler.py", line 61, in handle
    return ver_handle(node, **kwargs)
  File "/data1/fujiayi/Project/GitHub/onnx-tensorflow/onnx_tf/handlers/backend/slice.py", line 59, in version_10
    input_tensor_shape = tf.constant(input_tensor.shape.dims, ends.dtype)
  File "/data1/fujiayi/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 180, in constant_v1
    allow_broadcast=False)
  File "/data1/fujiayi/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/data1/fujiayi/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 467, in make_tensor_proto
    nparray = np.array(values, dtype=np_dt)
TypeError: __int__ returned non-int (type NoneType)

I debugged into the source codes and found the reason is that when it converts Slice Op, the shape of output tensor is None. And then if this tensor go into another Slice Op conversion it will crash in the line `input_tensor_shape = tf.constant(input_tensor.shape.dims, ends.dtype)`

**To Reproduce**

Just convert following ONNX model to TensorFlow.

**ONNX model file**

[model file](https://drive.google.com/open?id=1V9HKwQDXLFx7H0SvByn3K_fMqaexnguM)

**Python, ONNX, ONNX-TF, Tensorflow version**

 - Python version: 3.6
 - ONNX version: 1.5.0
 - ONNX-TF version: 1.5.0
 - Tensorflow version: 1.14.0

**Additional context**
The conversion is ok with onnx-tf 1.3.0.

**Comment by chinhuang007** [comment]
Thanks for reporting the bug. This seems introduced from a recent PR attempting to address negative axes. I am looking into a fix. If you want a quick solution when not having negative axes, just comment out L62-L64 should work.

**Comment by chinhuang007** [comment]
The PR, https://github.com/onnx/onnx-tensorflow/pull/528, under review should fix it.

**Comment by JiayiFu** [comment]
> The PR, #528, under review should fix it.

Get it, thanks!

**Comment by mshahabi** [comment]
I am still getting the same error using the following versions:
Python version: 3.6
ONNX version: 1.5.0
ONNX-TF version: 1.5.0
Tensorflow version: 1.15.0
