### ISSUE TITLE
NotImplementedError: Constant version 11 is not implemented

### ISSUE THREAD

**Issue by avisrazo** [onnx/onnx-tensorflow#527]
Hi,
I am trying to convert a pytorch model to tensorflow via onnx.
I exported a valid onnx model.
When I call the 'prepare' process I get an error that claims that Constant version 11 is not implemented, as presented below:

    tf_rep = prepare(model_onnx, opset_version=11)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 55, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 75, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 129, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 224, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\handlers\handler.py", line 61, in handle
    exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\common\exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\common\exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: Constant version 11 is not implemented.

**Versions Info**:
Python Version: 3.7.4
Pytorch Version: '1.4.0.dev20191118'
TensorFlow version: '1.15.0-rc3'
onnx version" 1.6.0

**Comment by chinhuang007** [comment]
Looks like you have used an older version of onnx-tf. Please try pip install to pick up the latest release 1.5.0 or use the master from git repo. Either way constant opset=11 should be supported.

**Comment by aviaisr** [comment]
I'm using onnx-tf version 1.5.0.
I even uninstalled and reinstalled onnx-tf but I still get the same NotImplementedError

    tf_rep = prepare(model_onnx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 143, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 238, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\handlers\handler.py", line 62, in handle
    exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\common\exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\common\exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: Gather version 11 is not implemented.

**Comment by chinhuang007** [comment]
I noticed the error is now for 'Gather' operator which is indeed not yet updated for ONNX 1.6 opset 11.

**Comment by aviaisr** [comment]
Thank you. I'm waiting for this update.

**Comment by pluradj** [comment]
> I noticed the error is now for 'Gather' operator which is indeed not yet updated for ONNX 1.6 opset 11.

Gather support for opset 11 is fixed with #537 on `master` and #555 on `tf-1.x`

**Comment by pluradj** [comment]
Constant support for opset 11 was fixed with #487

**Comment by omria503** [comment]
I pulled the latest ONNX-TF version and I still see that 
**"Gather version 11 is not implemented."**
Can you please help?

**Comment by thomas-beznik** [comment]
Hello,
I also still have this error; any indication on how to solve it?

Thank you!

**Comment by chinhuang007** [comment]
If you are on Tensorflow 1.x, you need to do a source build from the "tf-1.x" branch. Please try the following and see if it helps.

git clone https://github.com/onnx/onnx-tensorflow.git
cd onnx-tensorflow
git checkout tf-1.x
pip install -e .

**Comment by chinhuang007** [comment]
@thomas-beznik Please reopen if you still have the problem.
