### ISSUE TITLE
NotImplementedError: Gather version 11 is not implemented

### ISSUE THREAD

**Issue by karanjakhar** [onnx/onnx-tensorflow#646]
I am converting Faster RCNN model from ONNX to Tensorflow. I getting this error. I tried various things like install onnx_tf from source. But nothing works.

**Comment by karanjakhar** [comment]
The above problem is solved. But I am getting NotImplementedError: Resize version 11 is not implemented.

**Comment by chinhuang007** [comment]
There is a PR on resize, https://github.com/onnx/onnx-tensorflow/pull/612. Feel free to try it now or after it is merged.

**Comment by BenSturgeon** [comment]
I'm still getting this error on the latest version of the onnx-tf library (version 1.5). 

I'm using tensorflow 1.15.2.

**Comment by silviobarra85** [comment]
> I am converting Faster RCNN model from ONNX to Tensorflow. I getting this error. I tried various things like install onnx_tf from source. But nothing works.

Hi. How did you solve the Gather 11 not implemented error?

**Comment by BenSturgeon** [comment]
> > I am converting Faster RCNN model from ONNX to Tensorflow. I getting this error. I tried various things like install onnx_tf from source. But nothing works.
> 
> Hi. How did you solve the Gather 11 not implemented error?

I found that upgrading to the latest version (onnx-tf 1.6) fixed the problem for me.
